function [reportName, statistics] = exportReport(recordList)
%%   Copyright (c) 2016 Jared M. Saletin, PhD and Stephanie M. Greer, PhD
%
%   This file is part of Húmë.
%
%   Húmë is free software: you can redistribute it and/or modify it
%   under the terms of the GNU General Public License as published by the
%   Free Software Foundation, either version 3 of the License, or (at your
%   option) any later version.
%
%   Húmë is distributed in the hope that it will be useful, but
%   WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%   General Public License for more details.
%
%   You should have received a copy of the GNU General Public License along
%   with Húmë.  If not, see <http://www.gnu.org/licenses/>.
%
%   Húmë is intended for research purposes only. Any commercial or medical
%   use of this software is prohibited. The authors accept no
%   responsibility for its use in this manner.
%%
      reportName = 'Standard Table';
      if nargin > 0
          
      setdbprefs('DataReturnFormat','Table');  
      
      c = getappdata(0,'Conn');
      if strcmp(c.Driver, 'org.sqlite.JDBC')
          db = '';
%          sl = 1;
          
      else
          db = 'SleepLabStats.';
      end
      
      [statistics] =  fetch(getappdata(0,'Conn'), ['SELECT ', ...
            '', db, 'idStudy.id, ', ...
            '', db, 'idStudy.study, ', ...
            '', db, 'EDFInfo.EDFname, ', ...
            '', db, 'EDFInfo.condition, ', ...
            '', db, 'scoredInfo.scorer, ', ...
            '', db, 'scoredInfo.record, ', ...
            '', db, 'lightsTimeInfo.lightsOff, ', ...
            '', db, 'TDT.Minutes AS TDTmin, ', ...
            '', db, 'SPT.Minutes AS SPTmin, ', ...
            '', db, 'ROUND(SPT.TDTper*100, 1) AS [SPT_TDTper], ', ...
            '', db, 'TST.Minutes AS TSTmin, ', ...
            '', db, 'ROUND(TST.TDTper*100, 1) AS [TST_TDTper], ', ...
            '', db, 'ROUND(TST.SPTper*100, 1) AS [TST_SPTper], ', ...
            '', db, 'WAFA.Minutes AS WAFAmin, ', ...
            '', db, 'WASO.Minutes AS WASOmin, ', ...
            '', db, 'latencySleep.Minutes AS SleepLatency, ', ...
            '', db, 'latencySOREM.Minutes AS REML, ', ...
            '', db, 'TWT.Minutes AS TWTmin, ', ...
            '', db, 'ROUND(TWT.TSTper*100, 1) AS [TWT_TSTper], ', ...
            '', db, 'Stage1.Minutes AS [St1_min], ', ...
            '', db, 'ROUND(Stage1.TSTper*100, 1) AS [St1_TSTper], ', ...
            '', db, 'Stage2.Minutes AS [St2_min], ', ...
            '', db, 'ROUND(Stage2.TSTper*100, 1) AS [St2_TSTper], ', ...
            '', db, 'Stage3.Minutes AS [St3_min], ', ...
            '', db, 'ROUND(Stage3.TSTper*100, 1) AS [St3_TSTper], ', ...
            '', db, 'Stage4.Minutes AS [St4_min], ', ...
            '', db, 'ROUND(Stage4.TSTper*100, 1) AS [St4_TSTper], ', ...
            '', db, 'REM.Minutes AS [REM_min], ', ...
            '', db, 'ROUND(REM.TSTper*100, 1) AS [REM_TSTper], ', ...
            '', db, 'MT.Minutes AS [MT_min], ', ...
            '', db, 'ROUND(MT.TSTper*100, 1) AS [MT_TSTper], ', ...
            '', db, 'SW.Minutes AS [SW_min], ', ...
            '', db, 'ROUND(SW.TSTper*100, 1) AS [SW_TSTper], ', ...
            '', db, 'NREM.Minutes AS [NREM_min], ', ...
            '', db, 'ROUND(NREM.TSTper*100, 1) AS [NREM_TSTper], ', ...
            '', db, 'ThirdWake.T1 AS [Wake_min_T1], ', ...
            '', db, 'ThirdWake.T2 AS [Wake_min_T2], ', ...
            '', db, 'ThirdWake.T3 AS [Wake_min_T3], ', ...         
            '', db, 'ThirdS1.T1 AS [St1_min_T1], ', ...
            '', db, 'ThirdS1.T2 AS [St1_min_T2], ', ...
            '', db, 'ThirdS1.T3 AS [St1_min_T3], ', ...
            '', db, 'ThirdS2.T1 AS [St2_min_T1], ', ...
            '', db, 'ThirdS2.T2 AS [St2_min_T2], ', ...
            '', db, 'ThirdS2.T3 AS [St2_min_T3], ', ...
            '', db, 'ThirdS3.T1 AS [St3_min_T1], ', ...
            '', db, 'ThirdS3.T2 AS [St3_min_T2], ', ...
            '', db, 'ThirdS3.T3 AS [St3_min_T3], ', ...
            '', db, 'ThirdS4.T1 AS [St4_min_T1], ', ...
            '', db, 'ThirdS4.T2 AS [St4_min_T2], ', ...
            '', db, 'ThirdS4.T3 AS [St4_min_T3], ', ...
            '', db, 'ThirdREM.T1 AS [REM_min_T1], ', ...
            '', db, 'ThirdREM.T2 AS [REM_min_T2], ', ...
            '', db, 'ThirdREM.T3 AS [REM_min_T3], ', ...
            '', db, 'ThirdMT.T1 AS [MT_min_T1], ', ...
            '', db, 'ThirdMT.T2 AS [MT_min_T2], ', ...
            '', db, 'ThirdMT.T3 AS [MT_min_T3], ', ... 
            '', db, 'ThirdSW.T1 AS [SW_min_T1], ', ...
            '', db, 'ThirdSW.T2 AS [SW_min_T2], ', ...
            '', db, 'ThirdSW.T3 AS [SW_min_T3], ', ...      
            '', db, 'ThirdTotal.T1 AS [Total_min_T1], ', ...
            '', db, 'ThirdTotal.T2 AS [Total_min_T2], ', ...
            '', db, 'ThirdTotal.T3 AS [Total_min_T3] ', ...      
            'FROM ', ...
            '', db, 'EDFInfo ', ...
            'JOIN ', db, 'idStudy ', ...
            'ON ', db, 'EDFInfo.id = ', db, 'idStudy.id  ', ...
            'JOIN ', db, 'scoredInfo ', ...
            'ON ', db, 'scoredInfo.EDFname = ', db, 'EDFInfo.EDFname  ', ...
            'JOIN ', db, 'lightsTimeInfo ', ...
            'ON ', db, 'lightsTimeInfo.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'TST ', ...
            'ON ', db, 'TST.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'SPT ', ...
            'ON ', db, 'SPT.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'TDT ', ...
            'ON ', db, 'TDT.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'WAFA ', ...
            'ON ', db, 'WAFA.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'WASO ', ...
            'ON ', db, 'WASO.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'latencySleep ', ...
            'ON ', db, 'latencySleep.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'latencySOREM ', ...
            'ON ', db, 'latencySOREM.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'TWT ', ...
            'ON ', db, 'TWT.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'Stage1 ', ...
            'ON ', db, 'Stage1.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'Stage2 ', ...
            'ON ', db, 'Stage2.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'Stage3 ', ...
            'ON ', db, 'Stage3.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'Stage4 ', ...
            'ON ', db, 'Stage4.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'REM ', ...
            'ON ', db, 'REM.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'MT ', ...
            'ON ', db, 'MT.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'SW ', ...
            'ON ', db, 'SW.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'NREM ', ...
            'ON ', db, 'NREM.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'ThirdWake ', ...
            'ON ', db, 'ThirdWake.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'ThirdS1 ', ...
            'ON ', db, 'ThirdS1.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'ThirdS2 ', ...
            'ON ', db, 'ThirdS2.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'ThirdS3 ', ...
            'ON ', db, 'ThirdS3.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'ThirdS4 ', ...
            'ON ', db, 'ThirdS4.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'ThirdREM ', ...
            'ON ', db, 'ThirdREM.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'ThirdMT ', ...
            'ON ', db, 'ThirdMT.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'ThirdSW ', ...
            'ON ', db, 'ThirdSW.record = ', db, 'scoredInfo.record  ', ...
            'JOIN ', db, 'ThirdTotal ', ...
            'ON ', db, 'ThirdTotal.record = ', db, 'scoredInfo.record  ', ...
            'WHERE ', db, 'scoredInfo.record IN (',strjoin(strcat('''',recordList,''''),', '),');']);
            setdbprefs('DataReturnFormat','Table');
            
%             if sl
%                 statistics = cell2table(statistics, 'VariableNames', {'id','study','EDFname','condition','scorer','record','TDTmin','SPTmin','SPT_TDTper','TSTmin','TST_TDTper','TST_SPTper','WAFAmin','WASOmin','SleepLatency','REML','TWTmin','TWT_TSTper','St1_min','St1_TSTper','St2_min','St2_TSTper','St3_min','St3_TSTper','St4_min','St4_TSTper','REM_min','REM_TSTper','MT_min','MT_TSTper','SW_min','SW_TSTper','NREM_min','NREM_TSTper'});
%             end
                
      end
end
